/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ChaseFloodMsg'
 * message type.
 */

public class ChaseFloodMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 6;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 22;

    /** Create a new ChaseFloodMsg of size 6. */
    public ChaseFloodMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ChaseFloodMsg of the given data_length. */
    public ChaseFloodMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg with the given data_length
     * and base offset.
     */
    public ChaseFloodMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg using the given byte array
     * as backing store.
     */
    public ChaseFloodMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ChaseFloodMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ChaseFloodMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg embedded in the given message
     * at the given base offset.
     */
    public ChaseFloodMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ChaseFloodMsg embedded in the given message
     * at the given base offset and length.
     */
    public ChaseFloodMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ChaseFloodMsg> \n";
      try {
        s += "  [seq_no=0x"+Long.toHexString(get_seq_no())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [time_flood_h=0x"+Long.toHexString(get_time_flood_h())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [time_flood_l=0x"+Long.toHexString(get_time_flood_l())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: seq_no
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'seq_no' is signed (false).
     */
    public static boolean isSigned_seq_no() {
        return false;
    }

    /**
     * Return whether the field 'seq_no' is an array (false).
     */
    public static boolean isArray_seq_no() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'seq_no'
     */
    public static int offset_seq_no() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'seq_no'
     */
    public static int offsetBits_seq_no() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'seq_no'
     */
    public int get_seq_no() {
        return (int)getUIntBEElement(offsetBits_seq_no(), 16);
    }

    /**
     * Set the value of the field 'seq_no'
     */
    public void set_seq_no(int value) {
        setUIntBEElement(offsetBits_seq_no(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'seq_no'
     */
    public static int size_seq_no() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'seq_no'
     */
    public static int sizeBits_seq_no() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: time_flood_h
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'time_flood_h' is signed (false).
     */
    public static boolean isSigned_time_flood_h() {
        return false;
    }

    /**
     * Return whether the field 'time_flood_h' is an array (false).
     */
    public static boolean isArray_time_flood_h() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'time_flood_h'
     */
    public static int offset_time_flood_h() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'time_flood_h'
     */
    public static int offsetBits_time_flood_h() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'time_flood_h'
     */
    public int get_time_flood_h() {
        return (int)getUIntBEElement(offsetBits_time_flood_h(), 16);
    }

    /**
     * Set the value of the field 'time_flood_h'
     */
    public void set_time_flood_h(int value) {
        setUIntBEElement(offsetBits_time_flood_h(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'time_flood_h'
     */
    public static int size_time_flood_h() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'time_flood_h'
     */
    public static int sizeBits_time_flood_h() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: time_flood_l
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'time_flood_l' is signed (false).
     */
    public static boolean isSigned_time_flood_l() {
        return false;
    }

    /**
     * Return whether the field 'time_flood_l' is an array (false).
     */
    public static boolean isArray_time_flood_l() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'time_flood_l'
     */
    public static int offset_time_flood_l() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'time_flood_l'
     */
    public static int offsetBits_time_flood_l() {
        return 32;
    }

    /**
     * Return the value (as a int) of the field 'time_flood_l'
     */
    public int get_time_flood_l() {
        return (int)getUIntBEElement(offsetBits_time_flood_l(), 16);
    }

    /**
     * Set the value of the field 'time_flood_l'
     */
    public void set_time_flood_l(int value) {
        setUIntBEElement(offsetBits_time_flood_l(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'time_flood_l'
     */
    public static int size_time_flood_l() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'time_flood_l'
     */
    public static int sizeBits_time_flood_l() {
        return 16;
    }

}
